### ISSUE TITLE
CW308T-GENERIC

### ISSUE THREAD

**Issue by lukaskuzmiak** [newaetech/chipwhisperer-target-cw308t#4]
Is CW308T-GENERIC opensource? I was going to order some target boards and thought it would be nice to get more prototyping/generic ones but did not find gerbers for it.

Happy New Year!

**Comment by colinoflynn** [comment]
Oops! It *should* be... let me fix.

**Comment by colinoflynn** [comment]
Added - https://github.com/newaetech/chipwhisperer-target-cw308t/tree/master/CW308T_GENERIC/gerbers along with the altium source!
